"""Corpus fetch and page discovery (Tech.md §5.1, §5.2).

The corpus is the FastAPI repository at one pinned **tag**. Tags are the unit of reproducibility:
an index version records the tag and the commit SHA it resolved to, and re-ingesting the same tag
must see the same files. Branches are refused because they move.

Git runs as a subprocess with an argument list (no shell). Failures raise ``CorpusError`` with
git's own message: ingest is offline tooling and should stop loudly, not index half a corpus.
"""

from __future__ import annotations

import fnmatch
import logging
import re
import subprocess
from pathlib import Path
from typing import Final

from grounded.ingest.types import CorpusCheckout, PageRef

logger = logging.getLogger(__name__)

FASTAPI_REPO_URL: Final = "https://github.com/fastapi/fastapi.git"
DOCS_BASE_URL: Final = "https://fastapi.tiangolo.com"
# English docs inside the repo; other languages are translations of the same pages (PRD §5).
DOCS_DIR: Final = "docs/en/docs"

# Pages that exist under docs/en/docs but are not documentation text, as fnmatch patterns on the
# path relative to DOCS_DIR (``*`` also matches ``/``). Changing this list changes the corpus, so
# it is recorded in the index's chunking config and reviewed like any other corpus change.
EXCLUDED_PAGES: Final[dict[str, str]] = {
    "release-notes.md": "changelog (~700 KB of version bullets), not documentation",
    "external-links.md": "link lists generated by Jinja from data files we don't render",
    "fastapi-people.md": "contributor and sponsor lists generated by Jinja",
    "newsletter.md": "an embedded signup form, no text",
    "translation-banner.md": "banner snippet included into translated pages",
    "_llm-test.md": "test fixture for the translation prompts",
    "reference/*": "API reference rendered from docstrings; the Markdown holds `:::` directives",
    "js/*": "site assets",
    "css/*": "site assets",
    "img/*": "site assets",
}

# A tag name that is also a safe single path segment and can't be mistaken for a git option.
_REF_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*")
_EXPLICIT_ANCHOR_RE = re.compile(r"\s*\{\s*#[^}]*\}\s*$")
_FENCE_RE = re.compile(r"^\s{0,3}(`{3,}|~{3,})")
# Generous: a shallow clone of the FastAPI repo takes well under a minute on a normal connection.
_GIT_TIMEOUT_S: Final = 600


class CorpusError(Exception):
    """The corpus could not be fetched, verified or read."""


def fetch_corpus(ref: str, cache_dir: Path, *, repo_url: str = FASTAPI_REPO_URL) -> CorpusCheckout:
    """Shallow-clone ``repo_url`` at tag ``ref`` into ``<cache_dir>/corpus/<ref>``, or reuse it.

    A checkout is reused only if it is still exactly the tag: its local tag ref resolves to HEAD
    and the working tree has no changes or untracked files (a stray ``.md`` would become a page).
    Anything else is an error rather than a silent re-clone, because deleting the directory is the
    operator's call.
    """
    if not _REF_RE.fullmatch(ref):
        raise CorpusError(f"invalid tag name {ref!r}")
    dest = cache_dir / "corpus" / ref

    if dest.exists():
        sha = _verify_checkout(dest, ref)
        logger.info("corpus checkout reused", extra={"ref": ref, "sha": sha})
        return CorpusCheckout(path=dest, ref=ref, sha=sha)

    expected_sha = _remote_tag_sha(repo_url, ref)
    dest.parent.mkdir(parents=True, exist_ok=True)
    _git(
        "clone",
        "--quiet",
        "--depth=1",
        f"--branch={ref}",
        # Keep the files byte-identical to the tag on every OS. A global core.autocrlf=true (common
        # on Windows) would otherwise check out CRLF and change every content hash.
        "--config=core.autocrlf=false",
        "--config=advice.detachedHead=false",
        "--",
        repo_url,
        str(dest),
    )
    sha = _verify_checkout(dest, ref)
    if sha != expected_sha:
        raise CorpusError(f"tag {ref} moved during clone: remote {expected_sha}, cloned {sha}")
    logger.info("corpus cloned", extra={"ref": ref, "sha": sha})
    return CorpusCheckout(path=dest, ref=ref, sha=sha)


def discover_pages(root: Path) -> list[PageRef]:
    """Every indexable English docs page under ``root``, sorted by path for determinism."""
    docs_root = root / DOCS_DIR
    if not docs_root.is_dir():
        raise CorpusError(f"no {DOCS_DIR} directory under {root}")

    section_names: dict[str, str] = {}
    pages: list[PageRef] = []
    excluded = 0
    relative_paths = sorted(p.relative_to(docs_root).as_posix() for p in docs_root.rglob("*.md"))
    for rel in relative_paths:
        if is_excluded(rel):
            excluded += 1
            continue
        pages.append(
            PageRef(
                source_path=f"{DOCS_DIR}/{rel}",
                url=page_url(rel),
                nav_path=_nav_path(docs_root, rel, section_names),
            )
        )
    logger.info("pages discovered", extra={"pages": len(pages), "excluded": excluded})
    return pages


def is_excluded(docs_relative_path: str) -> bool:
    return any(fnmatch.fnmatchcase(docs_relative_path, pattern) for pattern in EXCLUDED_PAGES)


def page_url(docs_relative_path: str) -> str:
    """Canonical site URL of a page (mkdocs ``use_directory_urls``).

    ``index.md`` → ``/``, ``tutorial/index.md`` → ``/tutorial/``,
    ``tutorial/first-steps.md`` → ``/tutorial/first-steps/``.
    """
    stem = docs_relative_path.removesuffix(".md")
    if stem == "index":
        path = ""
    elif stem.endswith("/index"):
        path = stem.removesuffix("index")
    else:
        path = f"{stem}/"
    return f"{DOCS_BASE_URL}/{path}"


def read_title(path: Path) -> str | None:
    """The page's first H1, without its ``{ #anchor }``; ``None`` if the page has none.

    A line scan, not the full parser: enough to skip YAML front matter and fenced code, which is all
    the section index pages need. Page titles for chunks come from the Markdown parser.
    """
    lines = path.read_text(encoding="utf-8").splitlines()
    start = 0
    if lines and lines[0].strip() == "---":
        closing = next((i for i, line in enumerate(lines[1:], 1) if line.strip() == "---"), None)
        start = closing + 1 if closing is not None else 0
    fence: str | None = None
    for line in lines[start:]:
        match = _FENCE_RE.match(line)
        if match:
            marker = match.group(1)
            if fence is None:
                fence = marker
            elif marker[0] == fence[0] and len(marker) >= len(fence):
                fence = None
            continue
        if fence is None and line.startswith("# "):
            return _EXPLICIT_ANCHOR_RE.sub("", line[2:]).strip()
    return None


def _nav_path(docs_root: Path, rel: str, cache: dict[str, str]) -> tuple[str, ...]:
    """Section names of the directories enclosing a page, outermost first.

    The name of a section is the H1 of its ``index.md`` ("tutorial/" → "Tutorial - User Guide"),
    which is what the site navigation shows. A directory's own ``index.md`` is the section page
    itself, so its nav path stops at the parent.
    """
    parts = rel.split("/")[:-1]
    if rel.endswith("/index.md"):
        parts = parts[:-1]
    names: list[str] = []
    for depth in range(1, len(parts) + 1):
        directory = "/".join(parts[:depth])
        if directory not in cache:
            cache[directory] = _section_name(docs_root, directory)
        names.append(cache[directory])
    return tuple(names)


def _section_name(docs_root: Path, directory: str) -> str:
    index = docs_root / directory / "index.md"
    title = read_title(index) if index.is_file() else None
    if title:
        return title
    fallback = directory.rsplit("/", 1)[-1].replace("-", " ").replace("_", " ").title()
    logger.warning(
        "section has no index.md title; using directory name",
        extra={"directory": directory, "section": fallback},
    )
    return fallback


def _remote_tag_sha(repo_url: str, ref: str) -> str:
    """The commit a remote tag points to, or ``CorpusError`` if ``ref`` is not a tag there."""
    tag = f"refs/tags/{ref}"
    output = _git("ls-remote", "--tags", "--", repo_url, tag, f"{tag}^{{}}")
    refs: dict[str, str] = {}
    for line in output.splitlines():
        sha, _, name = line.partition("\t")
        refs[name] = sha
    # An annotated tag lists the tag object and, with ^{}, the commit it points to.
    sha = refs.get(f"{tag}^{{}}") or refs.get(tag)
    if sha is None:
        raise CorpusError(f"{ref!r} is not a tag in {repo_url} (the corpus must be a pinned tag)")
    return sha


def _verify_checkout(dest: Path, ref: str) -> str:
    not_a_checkout = f"{dest} is not a checkout of tag {ref}; delete the directory and re-run"
    # Without its own .git, git would walk up and answer for an enclosing repo (e.g. this one).
    if not (dest / ".git").exists():
        raise CorpusError(not_a_checkout)
    try:
        tag_sha = _git("rev-parse", "--verify", "--quiet", f"refs/tags/{ref}^{{commit}}", cwd=dest)
    except CorpusError as exc:
        raise CorpusError(not_a_checkout) from exc
    head = _git("rev-parse", "HEAD", cwd=dest)
    if head != tag_sha:
        raise CorpusError(f"{dest} is at {head}, not at tag {ref} ({tag_sha})")
    if _git("status", "--porcelain", cwd=dest):
        raise CorpusError(f"{dest} has local changes; delete the directory and re-run")
    return head


def _git(*args: str, cwd: Path | None = None) -> str:
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=cwd,
            capture_output=True,
            text=True,
            check=True,
            timeout=_GIT_TIMEOUT_S,
        )
    except FileNotFoundError as exc:
        raise CorpusError("git is not installed or not on PATH") from exc
    except subprocess.TimeoutExpired as exc:
        raise CorpusError(f"git {args[0]} timed out after {_GIT_TIMEOUT_S}s") from exc
    except subprocess.CalledProcessError as exc:
        detail = (exc.stderr or exc.stdout or "").strip() or f"exit code {exc.returncode}"
        raise CorpusError(f"git {args[0]} failed: {detail}") from exc
    return result.stdout.strip()
